In [5]:
import os
import numpy as np
import pandas as pd
import csv

In [2]:
title_akas_df = pd.read_csv('../data/latest-tsvs/title.akas.tsv', sep= '\t')
title_akas_df.language.unique()

/Users/abhinivesh/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

array(['\\N', 'ja', 'sv', 'en', 'tr', 'es', 'sr', 'cs', 'sk', 'fr', 'fa',
       'bg', 'ca', 'nl', 'qbn', 'pt', 'ru', 'uk', 'qbp', 'ar', 'cmn',
       'rn', 'bs', 'de', 'hi', 'yi', 'qbo', 'ka', 'hr', 'sl', 'he', 'tg',
       'kk', 'da', 'el', 'fi', 'it', 'gsw', 'gl', 'eu', 'yue', 'az', 'ms',
       'pl', 'mr', 'uz', 'th', 'ta', 'be', 'af', 'la', 'hy', 'ur', 'bn',
       'te', 'ml', 'lt', 'mk', 'et', 'lv', 'tl', 'id', 'gd', 'cy', 'qal',
       'gu', 'kn', 'ro', 'hu', 'pa', 'wo', 'no', 'is', 'sq', 'vi', 'ga',
       'zh', 'ps', 'zu', 'nqo', 'sd', 'xh', 'mi', 'ku', 'rm', 'su', 'jv',
       'prs', 'ky', 'fro', 'ko', 'haw', 'mn', 'lo', 'my', 'am', 'qac',
       'ne', 'myv', 'br', 'iu', 'st', 'tn', 'cr'], dtype=object)

In [3]:
len( title_akas_df[ title_akas_df.language == 'en' ] ) / len(title_akas_df)

0.009885196357462612

In [4]:
len( title_akas_df[ title_akas_df.language == 'en' ] )

236693

In [6]:
title_ids_en = set( title_akas_df[ title_akas_df.language == 'en' ]['titleId'] )

title_ids_en

{'tt0054107',
 'tt9431412',
 'tt4928988',
 'tt9343574',
 'tt0100472',
 'tt0271253',
 'tt1513892',
 'tt1764351',
 'tt0062688',
 'tt4809396',
 'tt9253188',
 'tt0092031',
 'tt0274616',
 'tt6333086',
 'tt0255674',
 'tt10594792',
 'tt0902293',
 'tt10226810',
 'tt0147770',
 'tt7002122',
 'tt0168367',
 'tt2243192',
 'tt12462094',
 'tt5255710',
 'tt1706670',
 'tt5542862',
 'tt0065084',
 'tt0080547',
 'tt0364792',
 'tt0100104',
 'tt12771918',
 'tt3145464',
 'tt6846134',
 'tt2556338',
 'tt9419884',
 'tt3550748',
 'tt3152062',
 'tt0058796',
 'tt1787759',
 'tt2125499',
 'tt1286547',
 'tt0355470',
 'tt6707806',
 'tt5180244',
 'tt0047370',
 'tt0054134',
 'tt0158302',
 'tt11891768',
 'tt1557568',
 'tt0043166',
 'tt12826950',
 'tt0464626',
 'tt4979558',
 'tt0172811',
 'tt4974230',
 'tt10230670',
 'tt2006374',
 'tt2300488',
 'tt3264810',
 'tt3801372',
 'tt0084011',
 'tt2351177',
 'tt1714864',
 'tt9060964',
 'tt0128998',
 'tt7428476',
 'tt4684710',
 'tt8130414',
 'tt7372916',
 'tt3580052',
 'tt0429078',
 'tt12782416',
 'tt1345722',
 'tt2446980',
 'tt4166498',
 'tt0056272',
 'tt5368218',
 'tt9603898',
 'tt0211426',
 'tt5604510',
 'tt11455708',
 'tt0198733',
 'tt6164762',
 'tt0413826',
 'tt0374440',
 'tt2063719',
 'tt8707146',
 'tt1778260',
 'tt1354540',
 'tt2483130',
 'tt0407377',
 'tt3039472',
 'tt1359768',
 'tt10525508',
 'tt0206720',
 'tt1933649',
 'tt4543578',
 'tt6090044',
 'tt0120307',
 'tt0434349',
 'tt0298329',
 'tt0884227',
 'tt1828338',
 'tt0084745',
 'tt0055320',
 'tt0087796',
 'tt0120157',
 'tt0286733',
 'tt9818060',
 'tt10922610',
 'tt0193851',
 'tt2735328',
 'tt0356590',
 'tt0175825',
 'tt5844488',
 'tt6371402',
 'tt5776858',
 'tt3794028',
 'tt0458130',
 'tt8520446',
 'tt0063159',
 'tt1300378',
 'tt0073097',
 'tt0826632',
 'tt5119048',
 'tt1496472',
 'tt1388780',
 'tt0093789',
 'tt2270438',
 'tt0468683',
 'tt1074205',
 'tt0062679',
 'tt0315290',
 'tt1259532',
 'tt2369356',
 'tt0062167',
 'tt6477270',
 'tt0056417',
 'tt8467296',
 'tt0069069',
 'tt9138078',
 'tt0111778',
 'tt1510814',
 'tt0231434',
 'tt2624780',
 'tt5990054',
 'tt0095200',
 'tt0289844',
 'tt0274760',
 'tt11295176',
 'tt11067726',
 'tt0350997',
 'tt0431225',
 'tt9134458',
 'tt1686313',
 'tt2109204',
 'tt1303213',
 'tt1966571',
 'tt0211046',
 'tt10850842',
 'tt0072019',
 'tt0087042',
 'tt2792764',
 'tt2145659',
 'tt0493464',
 'tt2124077',
 'tt0316003',
 'tt0861351',
 'tt5462522',
 'tt0390734',
 'tt7625906',
 'tt0387537',
 'tt0420080',
 'tt5378250',
 'tt6162502',
 'tt2360755',
 'tt0095291',
 'tt4291700',
 'tt10217614',
 'tt1339261',
 'tt0457896',
 'tt1456379',
 'tt6274898',
 'tt6891902',
 'tt9861706',
 'tt0187636',
 'tt13230940',
 'tt2387449',
 'tt12748350',
 'tt3526924',
 'tt0061125',
 'tt2578272',
 'tt2367527',
 'tt7231236',
 'tt0376782',
 'tt2491648',
 'tt0967250',
 'tt12484616',
 'tt0045281',
 'tt9418572',
 'tt12452430',
 'tt0017983',
 'tt0023633',
 'tt0186989',
 'tt0065782',
 'tt0770183',
 'tt0770438',
 'tt10687158',
 'tt0490299',
 'tt3530232',
 'tt0043335',
 'tt1607567',
 'tt0945365',
 'tt1880260',
 'tt8141458',
 'tt6333380',
 'tt0103617',
 'tt0316122',
 'tt1978447',
 'tt5504102',
 'tt7985654',
 'tt0183374',
 'tt0096218',
 'tt3953834',
 'tt3645988',
 'tt6684714',
 'tt4094724',
 'tt8051852',
 'tt5162022',
 'tt9095296',
 'tt8991740',
 'tt2172194',
 'tt2084903',
 'tt0114997',
 'tt10650772',
 'tt5175442',
 'tt0018037',
 'tt0296598',
 'tt5478478',
 'tt0120789',
 'tt0051267',
 'tt0342678',
 'tt0364641',
 'tt1578873',
 'tt5526916',
 'tt2368963',
 'tt5155110',
 'tt0276898',
 'tt0318687',
 'tt1481522',
 'tt6453158',
 'tt0220827',
 'tt0482527',
 'tt1623646',
 'tt2850834',
 'tt3492330',
 'tt5237544',
 'tt0082511',
 'tt11163040',
 'tt0040572',
 'tt0049906',
 'tt1362543',
 'tt4214834',
 'tt1711487',
 'tt12228014',
 'tt0107533',
 'tt8535472',
 'tt12702232',
 'tt0004693',
 'tt0292105',
 'tt1785935',
 'tt4590390',
 'tt0274573',
 'tt0076843',
 'tt0486139',
 'tt0144950',
 'tt0049086',
 'tt8799718',
 'tt2347277',
 'tt1732518',
 'tt4419214',
 'tt0119917',
 'tt0204635',
 'tt2049584',
 'tt2103275',
 'tt0141658',
 'tt3247346',
 'tt7085648',
 'tt0309782',
 'tt5670758',
 'tt0023280',
 'tt4998212',
 'tt7681902',
 'tt8050582',
 'tt3062096',
 'tt2361746',
 'tt0036980',
 'tt4876900',
 'tt0091296',
 'tt12598008',
 'tt1717630',
 'tt6664206',
 'tt2987732',
 'tt0195861',
 'tt1057866',
 'tt0192187',
 'tt8023406',
 'tt1340761',
 'tt0120150',
 'tt0062707',
 'tt0310370',
 'tt0288205',
 'tt12283344',
 'tt6218010',
 'tt0158488',
 'tt0037627',
 'tt0081283',
 'tt0825744',
 'tt5375004',
 'tt0294662',
 'tt1050719',
 'tt0159654',
 'tt1813893',
 'tt0832827',
 'tt0086696',
 'tt0282496',
 'tt0307077',
 'tt0281819',
 'tt7230668',
 'tt0988045',
 'tt0482600',
 'tt0459618',
 'tt0111738',
 'tt2917484',
 'tt0044400',
 'tt0048457',
 'tt7083426',
 'tt0244434',
 'tt0929753',
 'tt2255709',
 'tt12826550',
 'tt1719540',
 'tt9814242',
 'tt0120266',
 'tt0120338',
 'tt0429200',
 'tt0047216',
 'tt10752046',
 'tt2364897',
 'tt0328676',
 'tt10514488',
 'tt13167618',
 'tt0938346',
 'tt0380311',
 'tt0349742',
 'tt0081607',
 'tt5765020',
 'tt0045987',
 'tt0312043',
 'tt11487894',
 'tt10815850',
 'tt0272684',
 'tt5004722',
 'tt9191842',
 'tt10026502',
 'tt0217582',
 'tt0349789',
 'tt0348042',
 'tt0312493',
 'tt0111836',
 'tt0085868',
 'tt3588392',
 'tt4703656',
 'tt10225354',
 'tt0290815',
 'tt1363464',
 'tt0175972',
 'tt4219164',
 'tt0091046',
 'tt0334879',
 'tt6762280',
 'tt5862962',
 'tt0249336',
 'tt0022857',
 'tt0245027',
 'tt1518211',
 'tt7256504',
 'tt9626392',
 'tt1538282',
 'tt6540984',
 'tt0261072',
 'tt0418917',
 'tt0038794',
 'tt0359375',
 'tt0065103',
 'tt3801442',
 'tt0120510',
 'tt0199174',
 'tt3230780',
 'tt0205843',
 'tt0286960',
 'tt0203619',
 'tt1484897',
 'tt12159988',
 'tt12254818',
 'tt0041944',
 'tt4473806',
 'tt0232860',
 'tt7232394',
 'tt0211430',
 'tt2209298',
 'tt8322810',
 'tt0180779',
 'tt0481922',
 'tt0071287',
 'tt0150969',
 'tt1516549',
 'tt3349428',
 'tt0101440',
 'tt9737600',
 'tt0089029',
 'tt10148170',
 'tt5001718',
 'tt0431979',
 'tt8826642',
 'tt13084832',
 'tt7193510',
 'tt0098115',
 'tt11197040',
 'tt4265314',
 'tt0171902',
 'tt5850976',
 'tt4164722',
 'tt8168814',
 'tt4119504',
 'tt10125986',
 'tt0116783',
 'tt2158581',
 'tt6147954',
 'tt12619692',
 'tt8761322',
 'tt0430623',
 'tt2336245',
 'tt7697424',
 'tt3004762',
 'tt8432070',
 'tt0788222',
 'tt2248544',
 'tt0457189',
 'tt11697820',
 'tt1691602',
 'tt5763732',
 'tt1286654',
 'tt7292380',
 'tt0907681',
 'tt8090284',
 'tt0432048',
 'tt8329560',
 'tt0020451',
 'tt0092744',
 'tt1394270',
 'tt0193557',
 'tt8439750',
 'tt0270850',
 'tt0080610',
 'tt0451152',
 'tt5431284',
 'tt0222355',
 'tt0231844',
 'tt0255890',
 'tt1424781',
 'tt0320153',
 'tt0311381',
 'tt7907922',
 'tt1511381',
 'tt0058979',
 'tt0196662',
 'tt2011130',
 'tt2963070',
 'tt0045510',
 'tt1567285',
 'tt6398414',
 'tt1245666',
 'tt4228706',
 'tt0035085',
 'tt0081254',
 'tt8354642',
 'tt4257926',
 'tt11695950',
 'tt0488433',
 'tt1557533',
 'tt0376839',
 'tt0835821',
 'tt9049178',
 'tt0315327',
 'tt0259343',
 'tt0068284',
 'tt1833120',
 'tt11423166',
 'tt6796762',
 'tt7897324',
 'tt1729624',
 'tt1548603',
 'tt6677882',
 'tt0014181',
 'tt0216591',
 'tt12109904',
 'tt4071048',
 'tt0215963',
 'tt3691446',
 'tt1815848',
 'tt0356799',
 'tt0113640',
 'tt2407064',
 'tt10203762',
 'tt6387506',
 'tt10765852',
 'tt0203515',
 'tt9479034',
 'tt1334260',
 'tt0499148',
 'tt0078930',
 'tt0129135',
 'tt0317858',
 'tt2251864',
 'tt1961264',
 'tt11788332',
 'tt7252812',
 'tt2351275',
 'tt0782694',
 'tt5214104',
 'tt3334454',
 'tt0457472',
 'tt0199031',
 'tt6407994',
 'tt0196129',
 'tt1274738',
 'tt7988984',
 'tt13143626',
 'tt0105179',
 'tt0357691',
 'tt10530402',
 'tt4837880',
 'tt0392785',
 'tt0826606',
 'tt3230166',
 'tt6911408',
 'tt1548764',
 'tt5311102',
 'tt1718778',
 'tt0332056',
 'tt12182460',
 'tt12573086',
 'tt0307936',
 'tt0195036',
 'tt10942070',
 'tt11240632',
 'tt8983218',
 'tt0470302',
 'tt0226448',
 'tt2345623',
 'tt4016934',
 'tt11357304',
 'tt0370939',
 'tt0475590',
 'tt2186699',
 'tt4978702',
 'tt0410931',
 'tt7856872',
 'tt6315778',
 'tt11497834',
 'tt0071671',
 'tt1601819',
 'tt1585700',
 'tt0000213',
 'tt6119504',
 'tt0807847',
 'tt1985093',
 'tt0390875',
 'tt1333503',
 'tt1764532',
 'tt0094658',
 'tt0287748',
 'tt4857058',
 'tt3852012',
 'tt0079516',
 'tt0292466',
 'tt0039666',
 'tt9093140',
 'tt11547542',
 'tt3276050',
 'tt11741594',
 'tt5617878',
 'tt1532350',
 'tt7722938',
 'tt2450486',
 'tt0462570',
 'tt10433222',
 'tt1569437',
 'tt3560464',
 'tt11834642',
 'tt1769306',
 'tt1188986',
 'tt0011931',
 'tt8822398',
 'tt1804604',
 'tt0176056',
 'tt0023684',
 'tt7865528',
 'tt0261830',
 'tt0233310',
 'tt0077595',
 'tt0089459',
 'tt1639466',
 'tt1573000',
 'tt5963850',
 'tt4050646',
 'tt9339838',
 'tt0194382',
 'tt11018418',
 'tt0156926',
 'tt1062927',
 'tt0331167',
 'tt0424136',
 'tt0455944',
 'tt1961395',
 'tt5928420',
 'tt0183881',
 'tt2128485',
 'tt3842684',
 'tt0388039',
 'tt5238240',
 'tt0349509',
 'tt0094878',
 'tt0381163',
 'tt6869922',
 'tt7837564',
 'tt8464600',
 'tt0288556',
 'tt0087814',
 'tt0149677',
 'tt0312568',
 'tt7931938',
 'tt0287928',
 'tt0376589',
 'tt0056584',
 'tt5953298',
 'tt2499802',
 'tt0377119',
 'tt0041619',
 'tt10327394',
 'tt2047789',
 'tt2119474',
 'tt1433537',
 'tt0072535',
 'tt0879090',
 'tt6626694',
 'tt9694170',
 'tt3514882',
 'tt1804979',
 'tt0365398',
 'tt0445410',
 'tt0119304',
 'tt1582547',
 'tt2277862',
 'tt0177958',
 'tt9367402',
 'tt1745941',
 'tt0060486',
 'tt1829669',
 'tt0216945',
 'tt0168372',
 'tt0297418',
 'tt0454248',
 'tt0044426',
 'tt10314462',
 'tt0348150',
 'tt0939918',
 'tt0090200',
 'tt3657988',
 'tt0913413',
 'tt0352621',
 'tt0199197',
 'tt7381612',
 'tt3042926',
 'tt2079478',
 'tt0142235',
 'tt6668014',
 'tt0319734',
 'tt2758770',
 'tt0109173',
 'tt0042332',
 'tt0062052',
 'tt0068502',
 'tt0126814',
 'tt0119934',
 'tt0283832',
 'tt1387317',
 'tt9657840',
 'tt9814918',
 'tt6574272',
 'tt0065562',
 'tt0884072',
 'tt5451204',
 'tt9460582',
 'tt0050588',
 'tt0449062',
 'tt10456640',
 'tt9060390',
 'tt5482490',
 'tt4580124',
 'tt6971040',
 'tt1197627',
 'tt6251390',
 'tt3530328',
 'tt0338159',
 'tt0369750',
 'tt1543914',
 'tt6306090',
 'tt9015424',
 'tt1170358',
 'tt0314920',
 'tt1838495',
 'tt0281307',
 'tt0090644',
 'tt1519663',
 'tt0117803',
 'tt0067492',
 'tt0965684',
 'tt8050756',
 'tt2670376',
 'tt0378189',
 'tt8596604',
 'tt6047232',
 'tt0986233',
 'tt2094031',
 'tt0088202',
 'tt0261935',
 'tt3282220',
 'tt0072653',
 'tt6736532',
 'tt0077478',
 'tt0220627',
 'tt6941654',
 'tt9248882',
 'tt1155604',
 'tt7790894',
 'tt0459264',
 'tt7167986',
 'tt10074298',
 'tt4604612',
 'tt0174821',
 'tt3227380',
 'tt5198796',
 'tt11717746',
 'tt0079701',
 'tt3384246',
 'tt8517814',
 'tt7317428',
 'tt7943324',
 'tt1596748',
 'tt3102382',
 'tt0285593',
 'tt4471620',
 'tt0327679',
 'tt0212993',
 'tt0483754',
 'tt12792532',
 'tt1759650',
 'tt1382699',
 'tt8201170',
 'tt9179260',
 'tt0008411',
 'tt6984456',
 'tt0352832',
 'tt0041991',
 'tt0470685',
 'tt0904037',
 'tt3577702',
 'tt0133819',
 'tt0093962',
 'tt0122393',
 'tt2352064',
 'tt0376964',
 'tt0097395',
 'tt0298082',
 'tt11599404',
 'tt5133742',
 'tt0246059',
 'tt0135617',
 'tt0203222',
 'tt0067741',
 'tt1282140',
 'tt9198330',
 'tt7234936',
 'tt0106936',
 'tt0239676',
 'tt6612946',
 'tt9177092',
 'tt1345464',
 'tt8650030',
 'tt5544258',
 'tt1097220',
 'tt12479400',
 'tt1156395',
 'tt1850380',
 'tt0460364',
 'tt3416312',
 'tt6722248',
 'tt3571908',
 'tt1014070',
 'tt0143338',
 'tt0469507',
 'tt10787268',
 'tt6269704',
 'tt0231081',
 'tt7855702',
 'tt8354344',
 'tt5479948',
 'tt0284581',
 'tt0226037',
 'tt8504986',
 'tt0315303',
 'tt1560989',
 'tt1753965',
 'tt1462900',
 'tt1877631',
 'tt11273284',
 'tt0190419',
 'tt1932767',
 'tt0144528',
 'tt0411475',
 'tt8698956',
 'tt0072930',
 'tt0078282',
 'tt1683895',
 'tt1205520',
 'tt11685362',
 'tt0000159',
 'tt2127268',
 'tt0353496',
 'tt0049472',
 'tt4573344',
 'tt0172630',
 'tt3306638',
 'tt3346236',
 'tt2034645',
 'tt6194422',
 'tt2105067',
 'tt11279434',
 'tt0309618',
 'tt1213924',
 'tt0157411',
 'tt12901942',
 'tt0164732',
 'tt0375792',
 'tt0214121',
 'tt10348904',
 'tt7797642',
 'tt2196390',
 'tt1130993',
 'tt2904550',
 'tt10610230',
 'tt0299457',
 'tt0028454',
 'tt8273830',
 'tt11746702',
 'tt8695220',
 'tt11394168',
 'tt0282201',
 'tt0280106',
 'tt0843188',
 'tt0065164',
 'tt12181864',
 'tt12351596',
 'tt8663516',
 'tt12830820',
 'tt4396726',
 'tt0257362',
 'tt3595434',
 'tt1858473',
 'tt0060386',
 'tt0218124',
 'tt0021125',
 'tt0042879',
 'tt10885114',
 'tt0386880',
 'tt4729306',
 'tt7845308',
 'tt0843312',
 'tt3020904',
 'tt0387509',
 'tt0038937',
 'tt0063974',
 'tt0180322',
 'tt0108724',
 'tt0036220',
 'tt0040483',
 'tt0059909',
 'tt0213595',
 'tt1298590',
 'tt5607530',
 'tt0048056',
 'tt0064803',
 'tt2319283',
 'tt2128549',
 'tt0195429',
 'tt0334487',
 'tt1620620',
 'tt5455344',
 'tt5641202',
 'tt0319418',
 'tt6895746',
 'tt6139566',
 'tt2202296',
 'tt0206091',
 'tt0448438',
 'tt0277794',
 'tt4864584',
 'tt0265396',
 'tt6075476',
 'tt1339548',
 'tt10734292',
 'tt1421191',
 'tt0305144',
 'tt6950112',
 'tt7687768',
 'tt7938144',
 'tt0471394',
 'tt11535212',
 'tt2460768',
 'tt3183352',
 'tt3544556',
 'tt6846432',
 'tt5473988',
 'tt0156196',
 'tt8378030',
 'tt8956662',
 'tt0119927',
 'tt10967502',
 'tt11975350',
 'tt5785964',
 'tt9564730',
 'tt4542814',
 'tt1074964',
 'tt0069141',
 'tt0109235',
 'tt6857302',
 'tt0123274',
 'tt0263414',
 'tt5419442',
 'tt0218775',
 'tt0358216',
 'tt0472615',
 'tt0257789',
 'tt0314135',
 'tt11947106',
 'tt0059868',
 'tt2249512',
 'tt5464086',
 'tt0095277',
 'tt10592176',
 'tt0114682',
 'tt0040460',
 'tt5331912',
 'tt0967520',
 'tt4766960',
 'tt13303366',
 'tt0315239',
 'tt2191689',
 'tt3512226',
 'tt1373254',
 'tt2670454',
 'tt9404440',
 'tt2006791',
 'tt3171176',
 'tt4240848',
 'tt7354020',
 'tt3844362',
 'tt0097225',
 'tt9174026',
 'tt1825842',
 'tt0121416',
 'tt0196773',
 'tt0212435',
 'tt11121754',
 'tt1464470',
 'tt1753773',
 'tt0099124',
 'tt6716552',
 'tt0031260',
 'tt9426272',
 'tt0133338',
 'tt4635032',
 'tt0373718',
 'tt1496806',
 'tt1519618',
 'tt10463726',
 'tt8019962',
 'tt0190001',
 ...}

In [7]:
len(title_ids_en)

180739

In [8]:
title_akas_new = title_akas_df[ title_akas_df.language == 'en' ]
title_akas_new.head()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
99,tt0000012,10,The Arrival of a Train at La Ciotat,XWW,en,alternative,\N,0
114,tt0000012,24,The Arrival of a Train,XWW,en,imdbDisplay,\N,0
117,tt0000012,27,The Arrival of a Train,XEU,en,imdbDisplay,\N,0
172,tt0000016,1,Boat Leaving the Port,XWW,en,\N,informal title,0
261,tt0000029,4,Baby's Meal,XWW,en,\N,informal literal title,0

In [9]:
title_basics_df = pd.read_csv('../data/latest-tsvs/title.basics.tsv', sep= '\t')

len( title_basics_df.loc[ title_basics_df.tconst.isin(title_ids_en) ] ) / len(title_basics_df), len( title_basics_df.loc[ title_basics_df.tconst.isin(title_ids_en) ] )

/Users/abhinivesh/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(0.024791666295134168, 180722)

In [10]:
title_basics_new = title_basics_df.loc[ title_basics_df.tconst.isin(title_ids_en) ]

In [11]:
title_crew_df = pd.read_csv('../data/latest-tsvs/title.crew.tsv', sep= '\t')

len( title_crew_df.loc[ title_crew_df.tconst.isin(title_ids_en) ] ) / len(title_crew_df), len( title_crew_df.loc[ title_crew_df.tconst.isin(title_ids_en) ] )

(0.02478470042501105, 180737)

In [12]:
title_crew_new = title_crew_df.loc[ title_crew_df.tconst.isin(title_ids_en) ]

In [13]:
title_episode_df = pd.read_csv('../data/latest-tsvs/title.episode.tsv', sep= '\t')

len( title_episode_df.loc[ title_episode_df.parentTconst.isin(title_ids_en) ] ) / len(title_episode_df), len( title_episode_df.loc[ title_episode_df.parentTconst.isin(title_ids_en) ] )

(0.28255056849518356, 1484161)

In [14]:
title_episode_new = title_episode_df.loc[ title_episode_df.parentTconst.isin(title_ids_en) ]

In [15]:
title_principals_df = pd.read_csv('../data/latest-tsvs/title.principals.tsv', sep= '\t')

len( title_principals_df.loc[ title_principals_df.tconst.isin(title_ids_en) ] ) / len(title_principals_df), len( title_principals_df.loc[ title_principals_df.tconst.isin(title_ids_en) ] )

(0.03526285878345675, 1470673)

In [16]:
title_principals_new = title_principals_df.loc[ title_principals_df.tconst.isin(title_ids_en) ]

In [17]:
title_ratings_df = pd.read_csv('../data/latest-tsvs/title.ratings.tsv', sep= '\t')

len( title_ratings_df.loc[ title_ratings_df.tconst.isin(title_ids_en) ] ) / len(title_ratings_df), len( title_ratings_df.loc[ title_ratings_df.tconst.isin(title_ids_en) ] )

(0.11449060063177892, 124389)

In [18]:
title_ratings_new = title_ratings_df.loc[ title_ratings_df.tconst.isin(title_ids_en) ]

In [19]:
name_ids_en = set( title_principals_new.nconst )

In [21]:
name_basics_df = pd.read_csv('../data/latest-tsvs/name.basics.tsv', sep= '\t')

len( name_basics_df.loc[ name_basics_df.nconst.isin(name_ids_en) ] ) / len(name_basics_df), len( name_basics_df.loc[ name_basics_df.nconst.isin(name_ids_en) ] )

(0.05426646016336721, 567866)

In [23]:
name_basics_new = name_basics_df.loc[ name_basics_df.nconst.isin(name_ids_en) ]

In [25]:
title_akas_new.to_csv('../data/modified-tsvs/title.akas.tsv', sep= '\t')

In [26]:
title_basics_new.to_csv('../data/modified-tsvs/title.basics.tsv', sep= '\t')

In [27]:
title_crew_new.to_csv('../data/modified-tsvs/title.crew.tsv', sep= '\t')

In [28]:
title_episode_new.to_csv('../data/modified-tsvs/title.episode.tsv', sep= '\t')

In [29]:
title_principals_new.to_csv('../data/modified-tsvs/title.principals.tsv', sep= '\t')

In [30]:
title_ratings_new.to_csv('../data/modified-tsvs/title.ratings.tsv', sep= '\t')

In [31]:
name_basics_new.to_csv('../data/modified-tsvs/name.basics.tsv', sep= '\t')